import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch


# Arbitrary units
a = 1.0
# Normalization relation
A = 2**(5 / 4) / (a**(3 / 2) * np.pi**(1 / 4))
x = np.linspace(-5 * a, 5 * a, 10_000)

probability_density = A**2 * x**2 * np.exp(-2 * x**2 / a**2)

"""
AI DECLARATION: Most of the following code block was generated by Claude Haiku 4.5.
AI was only used for plotting and styling purposes, not for any calculations or physics.
I have verified that the code is corret and produces the desired plot
"""
plt.style.use('seaborn-v0_8-whitegrid')
fig, ax = plt.subplots(figsize=(10, 6), dpi=130)

ax.plot(x, probability_density, color='tab:blue', linewidth=2.2)
ax.axvline(0, color='black', linestyle='--', linewidth=1.2)
delta_x = np.sqrt(3) * a / 2
ax.axvline(-delta_x, color='tab:orange', linestyle=':', linewidth=1.2)
ax.axvline(delta_x, color='tab:orange', linestyle=':', linewidth=1.2)
ax.axvline(a, color='tab:green', linestyle='--', linewidth=1.2)
ax.fill_between(
	x,
	probability_density,
	where=(x >= 0) & (x <= a),
	color='tab:green',
	alpha=0.2,
)
ax.set_xticks(
	[-5 * a, -4 * a, -3 * a, -2 * a, -a, 0, a, 2 * a, 3 * a, 4 * a, 5 * a],
	)
ax.set_xticklabels(
	[r'$-5a$', r'$-4a$', r'$-3a$', r'$-2a$', r'$-a$', r'$0$', r'$a$', r'$2a$', r'$3a$', r'$4a$', r'$5a$'],
)
ax.set_xlabel(r'$x$', fontsize=12)
ax.set_ylabel(r'Probability density, $|\psi(x,0)|^2$', fontsize=12)
ax.set_title(r'Probability density for $\psi(x)=Ax\,e^{-x^2/a^2}$', fontsize=14, pad=12)
ax.set_xlim(-5 * a, 5 * a)
ax.set_ylim(bottom=0)
ax.grid(True, alpha=0.3)
ax.tick_params(direction='in', top=True, right=True)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

legend_handles = [
	Line2D([0], [0], color='tab:blue', linewidth=2.2, label=r'$|\psi(x)|^2$'),
	Line2D([0], [0], color='black', linestyle='--', linewidth=1.2, label=r'$\langle x\rangle=0$'),
	Line2D([0], [0], color='tab:orange', linestyle=':', linewidth=1.2, label=r'$\langle x\rangle\pm\Delta x$'),
	Line2D([0], [0], color='tab:green', linestyle='--', linewidth=1.2, label=r'$x=a$'),
	Patch(facecolor='tab:green', alpha=0.2, edgecolor='none', label=r'$P(0<x<a)\approx36.9\%$'),
]
ax.legend(handles=legend_handles, loc='upper right', frameon=True, framealpha=0.95, edgecolor='0.8')
fig.tight_layout()
plt.show()
